[platformio]
default_envs = cyd-dual-usb

[env]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
upload_protocol = esptool
upload_speed = 460800
monitor_speed = 115200
board_build.flash_mode = dio
board_build.f_flash = 40000000L
board_build.partitions = huge_app.csv
extra_scripts =
  pre:tools/platformio_framework_includes.py
build_src_filter =
  +<main.cpp>
build_flags =
  -std=gnu++14
  -DCORE_DEBUG_LEVEL=1
  -DUSER_SETUP_LOADED=1
  -include $PROJECT_DIR/User_Setup.h
  -I $PROJECT_DIR
lib_ldf_mode = deep+
lib_deps =
  bodmer/TFT_eSPI
  paulstoffregen/XPT2046_Touchscreen

[env:cyd-dual-usb]

[env:cyd-usb-c]
extends = env:cyd-dual-usb

[env:cyd-micro-usb]
extends = env:cyd-dual-usb
